In [42]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [43]:
df = pd.read_csv('cleaned_data.csv')
df.sample()

,age,RevolvingUtilizationOfUnsecuredLines,NumberOfTime30-59DaysPastDueNotWorse,NumberOfTime60-89DaysPastDueNotWorse,NumberOfTimes90DaysLate,DebtRatio,DebtRatioMissing,MonthlyIncome,NumberOfOpenCreditLinesAndLoans,NumberRealEstateLoansOrLines,NumberOfDependents,SeriousDlqin2yrs
117751,36,0.088658,0,0,0,0.226616,0,4500.0,4,2,0.0,0

In [44]:
df['LogIncome'] = np.log(df['MonthlyIncome'])

In [45]:
df.drop(['MonthlyIncome'],axis=1,inplace=True)

In [46]:
bins = [19, 35, 50, 65, float('inf')]
labels = ['Young', 'Middle-aged', 'Senior', 'Old'] # 

df['AgeGroup'] = pd.cut(df['age'],bins=bins,labels=labels)

In [47]:
df = pd.get_dummies(df,columns=['AgeGroup'],drop_first=True,dtype=int)

In [48]:
df

,age,RevolvingUtilizationOfUnsecuredLines,NumberOfTime30-59DaysPastDueNotWorse,NumberOfTime60-89DaysPastDueNotWorse,NumberOfTimes90DaysLate,DebtRatio,DebtRatioMissing,NumberOfOpenCreditLinesAndLoans,NumberRealEstateLoansOrLines,NumberOfDependents,SeriousDlqin2yrs,LogIncome,AgeGroup_Middle-aged,AgeGroup_Senior,AgeGroup_Old
0,45,0.766127,2,0,0,0.802982,0,13,6,2.0,1,9.118225,1,0,0
1,40,0.957151,0,0,0,0.121876,0,4,0,1.0,0,7.863267,1,0,0
2,38,0.658180,1,0,1,0.085113,0,2,0,0.0,0,8.020270,1,0,0
3,30,0.233810,0,0,0,0.036050,0,5,0,0.0,0,8.101678,0,0,0
4,49,0.907239,1,0,0,0.024926,0,7,1,0.0,0,11.060180,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
134201,74,0.040674,0,0,0,0.225131,0,4,1,0.0,0,7.649693,0,0,1
134202,44,0.299745,0,0,0,0.716562,0,4,1,2.0,0,8.627661,1,0,0
134203,58,0.246044,0,0,0,0.291184,1,18,1,0.0,0,8.261010,0,1,0
134204,30,0.000000,0,0,0,0.000000,0,4,0,0.0,0,8.651025,0,0,0
134205,64,0.850283,0,0,0,0.249908,0,8,2,0.0,0,9.006754,0,1,0

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134206 entries, 0 to 134205
Data columns (total 15 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   age                                   134206 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  134206 non-null  float64
 2   NumberOfTime30-59DaysPastDueNotWorse  134206 non-null  int64
 3   NumberOfTime60-89DaysPastDueNotWorse  134206 non-null  int64
 4   NumberOfTimes90DaysLate               134206 non-null  int64
 5   DebtRatio                             134206 non-null  float64
 6   DebtRatioMissing                      134206 non-null  int64
 7   NumberOfOpenCreditLinesAndLoans       134206 non-null  int64
 8   NumberRealEstateLoansOrLines          134206 non-null  int64
 9   NumberOfDependents                    134206 non-null  float64
 10  SeriousDlqin2yrs                      134206 non-null  int64
 11  LogIncome                             134206 non-null  float64
 12  AgeGroup_Middle-aged                  134206 non-null  int32
 13  AgeGroup_Senior                       134206 non-null  int32
 14  AgeGroup_Old                          134206 non-null  int32
dtypes: float64(4), int32(3), int64(8)
memory usage: 13.8 MB

In [50]:
df.columns

Index(['age', 'RevolvingUtilizationOfUnsecuredLines',
       'NumberOfTime30-59DaysPastDueNotWorse',
       'NumberOfTime60-89DaysPastDueNotWorse', 'NumberOfTimes90DaysLate',
       'DebtRatio', 'DebtRatioMissing', 'NumberOfOpenCreditLinesAndLoans',
       'NumberRealEstateLoansOrLines', 'NumberOfDependents',
       'SeriousDlqin2yrs', 'LogIncome', 'AgeGroup_Middle-aged',
       'AgeGroup_Senior', 'AgeGroup_Old'],
      dtype='object')

In [51]:
df = df[['age', 'RevolvingUtilizationOfUnsecuredLines','NumberOfTime30-59DaysPastDueNotWorse',
         'NumberOfTime60-89DaysPastDueNotWorse', 'NumberOfTimes90DaysLate','DebtRatio', 'DebtRatioMissing', 
         'NumberOfOpenCreditLinesAndLoans','NumberRealEstateLoansOrLines', 'NumberOfDependents', 
         'LogIncome', 'AgeGroup_Middle-aged','AgeGroup_Senior', 'AgeGroup_Old','SeriousDlqin2yrs']]

In [52]:
from sklearn.preprocessing import StandardScaler,RobustScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [53]:
Transformer = ColumnTransformer([
    ('StandardScaling',StandardScaler(),['age', 'RevolvingUtilizationOfUnsecuredLines', 'LogIncome', 'NumberOfOpenCreditLinesAndLoans']),
    ('RobustScaling',RobustScaler(),['DebtRatio', 'NumberOfTime30-59DaysPastDueNotWorse', 'NumberOfTime60-89DaysPastDueNotWorse', 
                                     'NumberOfTimes90DaysLate', 'NumberRealEstateLoansOrLines', 'NumberOfDependents']),
],remainder='passthrough')

In [54]:
X = df.iloc[:,:-1]
y = df.iloc[:,-1]

In [55]:
from sklearn.model_selection import train_test_split

In [56]:
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)

In [57]:
from sklearn.linear_model import LogisticRegression

In [58]:
from imblearn.pipeline import Pipeline

In [59]:
from imblearn.over_sampling import SMOTENC

In [60]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 100654 entries, 83638 to 121958
Data columns (total 14 columns):
 #   Column                                Non-Null Count   Dtype
---  ------                                --------------   -----
 0   age                                   100654 non-null  int64
 1   RevolvingUtilizationOfUnsecuredLines  100654 non-null  float64
 2   NumberOfTime30-59DaysPastDueNotWorse  100654 non-null  int64
 3   NumberOfTime60-89DaysPastDueNotWorse  100654 non-null  int64
 4   NumberOfTimes90DaysLate               100654 non-null  int64
 5   DebtRatio                             100654 non-null  float64
 6   DebtRatioMissing                      100654 non-null  int64
 7   NumberOfOpenCreditLinesAndLoans       100654 non-null  int64
 8   NumberRealEstateLoansOrLines          100654 non-null  int64
 9   NumberOfDependents                    100654 non-null  float64
 10  LogIncome                             100654 non-null  float64
 11  AgeGroup_Middle-aged                  100654 non-null  int32
 12  AgeGroup_Senior                       100654 non-null  int32
 13  AgeGroup_Old                          100654 non-null  int32
dtypes: float64(4), int32(3), int64(7)
memory usage: 10.4 MB

In [61]:
smotenc = SMOTENC(categorical_features=[6,11,12,13],random_state=42)

In [62]:
Logistic_pipe = Pipeline(
    [
     ('SMOTENC',smotenc),
     ('Preprocessing',Transformer),
     ('Logistic Model',LogisticRegression())
    ]
)

In [63]:
from sklearn.model_selection import GridSearchCV

In [64]:
Logistic_parameters = {
    'Logistic Model__C':[100,10,1,0.1,0.01]
    }

Logistic_grid = GridSearchCV(Logistic_pipe,param_grid=Logistic_parameters,scoring='recall')

In [65]:
Logistic_grid.fit(X_train,y_train)

C:\Users\bhavy\anaconda3\Lib\site-packages\sklearn\compose\_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

GridSearchCV(estimator=Pipeline(steps=[('SMOTENC',
                                        SMOTENC(categorical_features=[6, 11, 12,
                                                                      13],
                                                random_state=42)),
                                       ('Preprocessing',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('StandardScaling',
                                                                         StandardScaler(),
                                                                         ['age',
                                                                          'RevolvingUtilizationOfUnsecuredLines',
                                                                          'LogIncome',
                                                                          'NumberOfOpenCreditLinesAndLoans']),
                                                                        ('RobustScaling',
                                                                         RobustScaler(),
                                                                         ['DebtRatio',
                                                                          'NumberOfTime30-59DaysPastDueNotWorse',
                                                                          'NumberOfTime60-89DaysPastDueNotWorse',
                                                                          'NumberOfTimes90DaysLate',
                                                                          'NumberRealEstateLoansOrLines',
                                                                          'NumberOfDependents'])])),
                                       ('Logistic Model',
                                        LogisticRegression())]),
             param_grid={'Logistic Model__C': [100, 10, 1, 0.1, 0.01]},
             scoring='recall')

In [66]:
Logistic_grid.best_params_

{'Logistic Model__C': 1}

In [67]:
y_preds = Logistic_grid.predict(X_test)

In [68]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, recall_score

In [69]:
accuracy_score(y_test,y_preds)

0.7569742489270386

In [70]:
recall_score(y_test,y_preds)

0.7279260780287474

In [71]:
print('Confusion Matrix')
print(confusion_matrix(y_test,y_preds))

Confusion Matrix
[[23980  7624]
 [  530  1418]]

In [72]:
print('Classification report')
print(classification_report(y_test,y_preds))

Classification report
              precision    recall  f1-score   support

           0       0.98      0.76      0.85     31604
           1       0.16      0.73      0.26      1948

    accuracy                           0.76     33552
   macro avg       0.57      0.74      0.56     33552
weighted avg       0.93      0.76      0.82     33552